name: Build Docs
on:
  push:
    branches: [ "*" ]

jobs:
  build:
    name: build-doc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install template
      run: |
        python -m pip install --upgrade pip
        pip install furo

    - name: Install dependencies
      run: |
          pip install aiohttp asyncio requests
          cd docs
          make clean html
          make html
          cd ..
          mv docs/_build/html/* .
          rm -rf docs venv __pycache__ trengine .gitignore LICENSE .github README.md pyproject.toml examples
          touch .nojekyll
          git checkout --orphan gh-pages
          git add . -A
          git config user.email "162994967+2ei@users.noreply.github.com"
          git config user.name "GitHub Action <Zaid>"
          git commit -m "Auto update docs"
          git push origin HEAD:gh-pages --force